name: 'BrowserStack Test'
on: [push, pull_request]

jobs:
  ubuntu-job:

    runs-on: ubuntu-latest
    steps:


    - name: 'Checkout the repository'
      uses: actions/checkout@v2

    - name: 'BrowserStack Env Setup'
      uses: 'browserstack/github-actions@master'
      with:
        username:  ${{ secrets.USERNAMEBS }}
        access-key: ${{ secrets.KEYBS }}

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        robot -d ../logs/ scenarios
        
          