name: 'BrowserStack Test'
on: [push, pull_request]

jobs:
  ubuntu-job:

    runs-on: ubuntu-latest
    steps:


    - name: 'Checkout the repository'
      uses: actions/checkout@v2

    - name: 'BrowserStack Env Setup'
      uses: 'browserstack/github-actions@master'
      with:
        username:  ${{ secrets.USERNAME }}
        access-key: ${{ secrets.KEY }}

    - name: Install python dependencies
      run: |
        pip install robotframework
        pip install --upgrade robotframework-appiumlibrary
        robot -d ../logs/ scenarios
        
          